### ISSUE TITLE
Wowhead WOTLK URLs appear to not parse correctly.

### ISSUE THREAD

**Issue by Winterbeetle** [mikeacjones/IcyVeinsTalentSequence#4]
With Talented installed, I can get the TalentSequence2 frame to show up anchored to Talented's UI. The pasted talent string from a WOTLK talent calculator URL doesn't appear to import correctly, however.

I get the following error popup from Swatter when I try to import:
```
ID: 27
Error occured in: Global
Count: 1
Message: ..\AddOns\TalentSequence2\WowheadTalents.lua line 39:
   Usage: GetTalentInfo(tabIndex, talentIndex[, isInspect[, isPet[, groupIndex]]])
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@TalentSequence2\WowheadTalents.lua"]:39: GetTalents()
   [string "@TalentSequence2\TalentSequence.lua"]:136: ImportTalents()
   [string "@TalentSequence2\TalentSequence.lua"]:46: OnAccept()
   [string "@..\FrameXML\StaticPopup.lua"]:5228: StaticPopup_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
```

**Comment by mikeacjones** [comment]
Ah. I haven't played wow in a while @EGDWind - I'll take a look at this in a bit to see what changed. With the launch of WOTLK they will have all changed.

**Comment by mikeacjones** [comment]
@EGDWind  - to confirm, your URL has letters in it at the end, right? You had the talent order panel open so that it maintained the order of the talents?

**Comment by Winterbeetle** [comment]
Correct, reopening the same URL in a private browser resulted in it having the same talent sequence present rather than the sequence data being lost. Sample URL:

https://www.wowhead.com/wotlk/talent-calc/mage/235025233102330153323102515321_001wr211q1b21q1y31rj541rj451rj7/0CBffJkfPffsQtZWyXaOuL4497-444ttttgnaHgnEV

**Comment by mikeacjones** [comment]
I keep clicking close with comment dang it.. can you test a change for me? It looks like they added more characters to support the additional talents and some change in the logic.

Can you manually update the WowheadTalents.lua to this: https://github.com/mikeacjones/TalentSequence2/blob/wotlk-main/WowheadTalents.lua
and see if it imports?

**Comment by Winterbeetle** [comment]
No dice, unfortunately:
```
Date: 2022-09-07 10:41:51
ID: 9
Error occured in: Global
Count: 1
Message: ..\AddOns\TalentSequence2\WowheadTalents.lua line 42:
   Usage: GetTalentInfo(tabIndex, talentIndex[, isInspect[, isPet[, groupIndex]]])
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@TalentSequence2\WowheadTalents.lua"]:42: GetTalents()
   [string "@TalentSequence2\TalentSequence.lua"]:136: ImportTalents()
   [string "@TalentSequence2\TalentSequence.lua"]:46: OnAccept()
   [string "@..\FrameXML\StaticPopup.lua"]:5228: StaticPopup_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
```

**Comment by mikeacjones** [comment]
Unfortunately testing isn't easy without a subscription. I'll see what I can test once I'm outside of work.

**Comment by mikeacjones** [comment]
@EGDWind  - Do they offer trials these days? I would hate to sub for a month just to do some testing 😅
Fairly confident this is just an indexing issue. The talents are in the pattern of a, b, c, d, etc as indexing for the talents. Where a capital letter means go to max in a single series (ie: A means max out the first talent in sequence). They added more letters for WOTLK, and then ran out of letters so are now using numbers too. The end-tier talents are now an even number (eg 4) where +1 of that represents max (ie: 5 means talent represented by 4, maxed in a series). Other than that nothing else has changed so that should be it.

**Comment by Winterbeetle** [comment]
Sadly, not that I know of; I just checked the new retail recruit-a-friend with a test account, but it doesn't seem to add game time like some of the old ones might've(?), and the test account couldn't log into classic as a result.

**Comment by mikeacjones** [comment]
I just went ahead and subbed. I'm looking at it and it looks like one of the big issues is that talents from `GetTalentInfo` seem to not be in the same visual order like they were previously... this is going to complicate things a bit heh.

**Comment by mikeacjones** [comment]
@EGDWind  can you give this a try?
https://github.com/mikeacjones/TalentSequence2/releases/download/wotlk-3.2.0/TalentSequence2-3.2.0-wotlk-main.zip

**Comment by Winterbeetle** [comment]
Let's see...

It appears to have worked properly for the build I linked above, but I tried another multi-tree build and it seems to have inserted extra talents.

https://www.wowhead.com/wotlk/talent-calc/mage/230025233102330150323102515321--023003_001wr211q1b21q1y31rj541rj451rj7/0BAFkJgPqqsqtttZWyXhOuL4497-444tthhgE2CbbF0N

This resulted in a 73/0/2 build ending at level 84 in-game.

**Comment by mikeacjones** [comment]
Ah.. I see the problem. Man the fact that I can't just use the index for it to line up is annoying.

**Comment by mikeacjones** [comment]
Give this a try: https://github.com/mikeacjones/TalentSequence2/releases/download/wotlk-3.2.1/TalentSequence2-3.2.1-wotlk-main.zip

**Comment by Winterbeetle** [comment]
That appears to work! I haven't tested any Icy Veins stuff yet, but now all my (mage, at least :-P) wowhead links seem to work!

Thank you for the fix!

**Comment by Winterbeetle** [comment]
(Also, it's showing up next to the regular talent window without needing Talented again, so that's good.)

**Comment by mikeacjones** [comment]
For now I'm just removing the IcyVeins module. Isn't that much work to transpose them. Eventually.. maybe.. I'll go see how the mapping in IcyVeins changed and get it updated. The hard part this go around was having to build a talent map first, rather than directly mapping the index to the talent. Annoying but quick enough fix I suppose.
